trigger:
  - DEV  # Change this to 'main' if you want to trigger on main branch commits

pool:
  name: Default  # Use the correct agent pool name where your self-hosted agent is running
  demands:
    - Agent.Name -equals AgentSelfHosted  # Ensure the correct agent is selected

steps:
  - checkout: self:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
